# name: Dart CI

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/setup-java@v1
#         with:
#           java-version: '12.x'
#       - uses: subosito/flutter-action@v1.3.2
#         with:
#           channel: 'stable'
#       - run: flutter pub get
#       - run: flutter test
#       - run: export JPUSH_KEY=${{ secrets.JPUSH_KEY }}
#       - run: echo >> android/local.properties 'JPUSH_KEY=${{ secrets.JPUSH_KEY }}'
#       # - run: echo >> lib/_key.dart 'const UMENG_KEY = "${{ secrets.UMENG_KEY }}";'
#       - run: flutter -v build apk
#       - name: Set Git Config
#         run: git config --global user.name ${{ secrets.GIT_USER_NAME }} &&  git config --global user.email ${{ secrets.GIT_EMAL }}
#       - name: Clone and push apk to clicli.me
#         run: git clone https://${{ secrets.GH_TOKEN }}@github.com/cliclitv/app.clicli.me.git && cd ./app.clicli.me && mv ../build/app/outputs/apk/release/* ./ && git add -A && git commit -m 'update release' &&  git push -f https://${{ secrets.GH_TOKEN }}@github.com/cliclitv/app.clicli.me.git
